#!/usr/bin/env bash
# Configure the Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" >> /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
REDIRECT_301="\\\trewrite ^/redirect_me https://google.com permanent;"
sudo sed -i "41i $REDIRECT_301" /etc/nginx/sites-available/default
REDIRECT_404="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "44i $REDIRECT_404" /etc/nginx/sites-available/default
sudo service nginx start
