#!/usr/bin/env bash
# CONFIGigure server with: HAproxy version 1.5 or greater
apt-get update -y
apt-get install -y haproxy

CONFIG="\
frontend main
	bind *:80
	mode http
	default_backend web-server
backend web-server
	balance roundrobin
	server 1845-web-01 35.185.122.18:80 check
	server 1845-web-02 35.237.15.1:80 check
"

sudo echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart