#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with while loop
contador=0
termina=10
while [ $termina -ge $contador ]
do
    echo "Holberton School"
    let contador=$contador+1
done
