#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with while loop
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Holberton School for the other iterations

counter=1

while [ $counter -le 10 ]
do
    if [[ "$counter" == '4' ]]
    then
	echo "bad luck"
    elif [[ "$counter" == '8' ]]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let counter=$counter+1
done
