#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes with while loop:
# display hours from 0 to 12
#display minutes from 1 to 59

hours=0
while [ $hours -le 12 ]
do
    echo "Hour: $hours"
    let hours=$hours+1
    minutes=1
    while [ $minutes -le 59 ]
    do
	echo "$minutes"
	let minutes=$minutes+1
    done
done
