#!/usr/bin/env bash
# Write a Bash script that displays with for loop:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

file="$(ls)"
for i in "$file"
do
    echo "$file" | cut -f2 -d "-"
done
